OPENAI_API_KEY = "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"
TAVILY_API_KEY = "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"
